### ISSUE TITLE
Progression is impossible

### ISSUE THREAD

**Issue by Cooliosity** [Globox1997/EarlyStage#4]
I stated the issue in german in #1 as I thought there was some kind of language barrier, but since you want me to remain in english, I'll do that.
As already stated by NoobiusMcGuffin, playing Minecraft with this mod in it's current state is impossible due to a very simple oversight: To get the flint axe you need wood to craft a crafting table and to get wood you need a flint axe. Please fix. 

Steps to reproduce: 
1. Create a new survival world and of course, don't cheat!
2. Try to obtain a crafting table.

Exptected behaviour: Obtaining a crafting table is possible.
Current behaviour: Obtaining a crafting table is impossible.

**Comment by Globox1997** [comment]
Ah now I get it..
Let me think about a solution

**Comment by darkblueofmagic** [comment]
Just discovered this mod today and already loved it because of its simplicity (fits right in vanilla, very immersive!). And yes, I am also here to address the progression oversight. 

My idea is to add a small recipe that creates 1 plank from 4 sticks (so the player can create planks right in their inventory, then progress to crafting table). This doesn't affect gameplay all that much, goes well with the simple-yet-immersive feeling of the mod, and (according to my *very limited* knowledge) should be relatively quick to implement.

Hope it helps and thank you very much for the awesome mod.

**Comment by Globox1997** [comment]
You will see what the next update includes :)

**Comment by Globox1997** [comment]
Added a crafting rock which closes the progression gap.
